# **createing array**

**1**

In [ ]:
import numpy as np
a=np.array([0,1,2,3,4,5,6,7,8,9])
print(a)

[0 1 2 3 4 5 6 7 8 9]


**2**

In [ ]:
import numpy as np
a=np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**3**

In [ ]:
import numpy as np
a=np.eye(3,3,k=0)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**4**

In [8]:
import numpy as np
from random import randint
a=np.random.rand(10)
print(a)

[0.44067267 0.48287611 0.81218913 0.08939718 0.25207281 0.77740197
 0.47537627 0.73120678 0.32391172 0.55735878]


**5**

In [ ]:
import numpy as np
a=np.zeros(10)
print(a)
b=np.ones(10)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


# **array indexing**

**6**

In [ ]:
import numpy as np
a=np.array([10,20,30,40,50])
print(a[2])

30


**7**

In [ ]:
import numpy as np
a=np.arange(1,17).reshape(4,4)
print(a)
print(a[1,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
7


**8**

In [ ]:
import numpy as np
a=np.array([5,10,15,20,25])
print(a[4])

25


**9**

In [ ]:
import numpy as np
a=np.array([1,3,5,7,9,11])
print([a[1],a[3],a[4]])   #or print(a[[1,3,4]])

[3, 7, 9]


**10**

In [ ]:
import numpy as np
a=np.arange(0,8).reshape(2,2,2)
print(a)
print(a[1,1,1])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
7


# **array slicing**

**11**

In [ ]:
import numpy as np
a=np.array([2,4,6,8,10,12])
print(a[:3])

[2 4 6]


**12**

In [10]:
# 12.Create a 4x4 array and slice it to get the first two rows and last two columns.
import numpy as np
a=np.arange(1,17).reshape(4,4)
print(a)
print("-----------------------------------")
print(a[:2])
print("-----------------------------------")
print(a[:,2:])
print("-----------------------------------")
print(a[:2,-2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
-----------------------------------
[[1 2 3 4]
 [5 6 7 8]]
-----------------------------------
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]
-----------------------------------
[[3 4]
 [7 8]]


**13**

In [ ]:
# 13.For the array a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), slice it to get every second element
import numpy as np
a=np.array([0,1,2,3,4,5,6,7,8,9])
print(a[0::2])

[0 2 4 6 8]


**14**

In [11]:
# 14.Slice the last two elements from each row of a 3x4 array.
import numpy as np
a=np.arange(1,13).reshape(3,4)
print(a)
print("----------------------")
print(a[:,-2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----------------------
[[ 3  4]
 [ 7  8]
 [11 12]]


**15**

In [ ]:
# 15: Create a 5x5 matrix and slice out the inner 3x3 matrix.
import numpy as np
a=np.arange(1,26).reshape(5,5)
print(a)
print("-------------------------------------")
print(a[1:4,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
-------------------------------------
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


# **data type**

**16**

In [ ]:
# 16.Create an array of integers from 0 to 5 and change its data type to float.
a=np.array([0,1,2,3,4,5])
a1=a.astype(dtype='f')
print(a1)

[0. 1. 2. 3. 4. 5.]


**17**

In [ ]:
# 17.Create a NumPy array of shape (3, 3) with boolean values (True/False).
a=np.arange(0,9).reshape(3,3)
print(a)
a1=a.astype(dtype=bool)
print(a1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[False  True  True]
 [ True  True  True]
 [ True  True  True]]


In [12]:
a=np.array([[True,False,True],[True,False,True],[True,False,True]])
print(a)

[[ True False  True]
 [ True False  True]
 [ True False  True]]


**18**

In [2]:
# 18.Create an array of complex numbers (e.g., [1+2j, 3+4j, 5+6j]).
import numpy as np
a=np.array([1,2,3,4])
print("orginal array:",a,a.dtype)
b=a.astype(complex)
print("new array:",b,b.dtype)

orginal array: [1 2 3 4] int64
new array: [1.+0.j 2.+0.j 3.+0.j 4.+0.j] complex128


**19**

In [13]:
# 19.Given an array of strings (e.g., ["1", "2", "3"]), convert it to an array of integers.
a=np.array(["1","2","3","4"])
print(a)
a1=a.astype(dtype='i')
print(a1)

['1' '2' '3' '4']
[1 2 3 4]


**20**

In [14]:
# 20.Create an array of float values and then convert it to an integer type.
a=np.array([1.1,2.1,3.1,4.1])
print(a)
a1=a.astype(dtype='i')
print(a1)

[1.1 2.1 3.1 4.1]
[1 2 3 4]
